# Generated by Django 4.1.3 on 2023-01-24 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_addres_order_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='merchant_id',
            new_name='payment_intent',
        ),
    ]
